### ISSUE TITLE
Multiplying?

### ISSUE THREAD

**Issue by MarkoSh** [julien-maurel/jQuery-Storage-API#33]
`storage.set('game.pairs.' + ilevel + '.' + isize + '.' + Date.now(), {
                                            scores: scores,
                                            errors: errors,
                                            time: timer.seconds
                                        });`

if ilevel|isize - is int, creates incorrect json. 1.9.1 - works good

**Comment by julien-maurel** [comment]
This plugin is not maintained but I check you issue on the new one.
In fact, issue is not that ilevel|isize is an int, but Date.now() return a very big int.
in 1.9.1, there was a bug, when index was an int, value was stored as an object, not as an array
Now it's fixed and stored as an array, if int is too big (like Date.now()), JSON can't encode because when you use JSON.stringify, empty cells are replace by null.
```
a=[]
a[5]='r'
JSON.stringify(a) // return "[null,null,null,null,null,"r"]" so if bigger index in array is too big, it failed
```

I can't fixed that. But you can change path use a string index and not just Date.now()
e.g add an "_" ('game.pairs.' + ilevel + '.' + isize + '._' + Date.now()), in this case an object will be stored
